### PR TITLE
[WIP] Add analysis notebook with sample trajectories

### PR DESCRIPTION
**Pull request by sukritsingh**
Starting a PR where I've added: 
1. An analysis notebook providing some basics of extracting features from MD simulations and plotting them (and some details) - `analyze-simulation.ipynb` 
2. A sample trajectory `sample-traj.dcd`
3. A sample PDB structure topology to load in with the trajectories `sample-structure.pdb`

This is currently a WIP PR so don't merge just yet. I think for the moment two questions should be answered: 
1. Are there any other features/ideas/useful questions that you would like to see addressed relative to the class? I think the only one I was going to add soon was going to be doing pairwise backbone RMSD based calculations to introduce the idea of "clustering by states"
2. More sophisticated analyses for trajectories, like Markov State Models, tend to require libraries like PyEMMA, etc., would it be alright to include those and assume the student's environment can import them? Core libraries being used now are `mdtraj`, `numpy` and `matplotlib`, so it would probably be just PyEmma added on.

Open to discussions here!

### CODE REVIEW

**Comment by yuanqing-wang** [comment]
Thanks @sukritsingh . Seeing that this is indeed a simple trajectory, would it be possible if you could reuse the trajectory generated in `hne.ipynb`? It would offer some continuity to the learning experience! I can correspondingly delete the analysis bits in the original notebook.

**Comment by yuanqing-wang** [comment]
also I like the idea of "clustering by states" and even introducing the Markov State Model.

**Comment by sukritsingh** [comment]
> Would it be possible if you could reuse the trajectory generated in hne.ipynb? It would offer some continuity to the learning experience! 

Sure! Happy to do so! I'll also go ahead and add on some of the corresponding analysis in the `analyze-simulation.ipynb` notebook and add it to this commit!

> also I like the idea of "clustering by states" and even introducing the Markov State Model.

Great to hear! I'll try tacking that on at the end of the notebook

**Comment by sukritsingh** [comment]
Alright I've made a few additional updates, summarized as:

1. I updated `hne.ipynb` to better test for stability using the OpenMM reporters, including making plots showing simulation stability!
2. I've added a separate notebook explaining and providing sample code noting how to make a Markov State Model (MSM), as well as explaining some basics. **Note**: MSMs work best even in examples when you have multiple trajectories, so rather than using the HNE trajectory, I set it to download a sample protein folding dataset of 28 trajectories and use them in RAM (it does not download any files into storage, so no additional files need to be pushed to gethub). It's relatively lightweight and even a basic macbook can hold all the trajectory data for the example.
3.  I've added an additional documentation to `analyze-simulation.ipynb` as well as additional code to compute RMSF and document it's connection to b-factors. 

@yuanqing-wang : Let me know if you need me to make any edits or additional points!

**Comment by sukritsingh** [comment]
Oh one additional point: 
1. I edited `hne.ipynb` to output a DCD trajectory file as well as the `output.pdb` file - this is so that it can be loaded more quickly into MDTraj, and from an education standpoint, shows how to do it the "standard" way with a topology file

**Comment by yuanqing-wang** [comment]
LGTM now! Please merge when you're done!

**Pull request merged**
